IEEE-754 compliance in float comparison operators
red/red pull request #4717
Opened 2020-11-10 18:32 UTC by hiiamboris

See PR #3902
Fixes #847, fixes #2567

2020-11-10 19:07 UTC, greggirwin commented
I love seeing all those tests. :+1: Looks like nice work.

2020-11-10 22:47 UTC, hiiamboris commented
I broke smth in compiler.r though :D Need to figure it out...

2020-11-11 02:30 UTC, qtxie reviewed
So this PR implemented `option 1` in https://github.com/red/red/issues/847#issuecomment-47734318 .
I'm not capable to review the code in the compiler. I reviewed all the tests, they're all OK. If the changes in the compiler are good, it's good to be merged.

2020-11-11 17:42 UTC, hiiamboris commented
`conditional-test.reds` succeeds on Bolek's RPi. Can't do nothing about it without reproducing :(

Same for the Red test suite:
```
boris@raspberrypi:~ $ ./run-all-comp1
~~~started test~~~ run-all-comp1




~~~finished test~~~  run-all-comp1
  Number of Tests Performed:      4470
  Number of Assertions Performed: 7830
  Number of Assertions Passed:    7830
  Number of Assertions Failed:    0

boris@raspberrypi:~ $ ./run-all-comp2
~~~started test~~~ run-all-comp2


ok
~~~finished test~~~  run-all-comp2
  Number of Tests Performed:      3084
  Number of Assertions Performed: 5683
  Number of Assertions Passed:    5683
  Number of Assertions Failed:    0
```

Will look into the Mac issue in a few days when I get more bandwidth to DL & set up a Mac VM.

2020-11-16 17:06 UTC, dockimbel commented on runtime/macros.reds
> +		if any [fl/value > 2147483647.0 fl/value < -2147483648.0 fl/value <> fl/value][
???

2020-11-16 22:47 UTC, qtxie commented on runtime/macros.reds
> +		if any [fl/value > 2147483647.0 fl/value < -2147483648.0 fl/value <> fl/value][
We have a function to test NaN in float.reds: `float/NaN?`

2020-11-17 09:40 UTC, dockimbel commented on runtime/macros.reds
> +		if any [fl/value > 2147483647.0 fl/value < -2147483648.0 fl/value <> fl/value][
I mean what is this `fl/value <> fl/value` part for?

2020-11-17 16:17 UTC, hiiamboris commented on runtime/macros.reds
> +		if any [fl/value > 2147483647.0 fl/value < -2147483648.0 fl/value <> fl/value][
To test for a NaN apparently ;)

2020-11-17 17:58 UTC, hiiamboris commented
On Mac 10.14 VM:
```
1s-Mac:xfer a1$ ./struct-test
~~~started test~~~ struct!
~~~finished test~~~ struct!
  Number of Tests Performed:      152
  Number of Assertions Performed: 571
  Number of Assertions Passed:    571
  Number of Assertions Failed:    0
```

2020-11-17 18:35 UTC, hiiamboris commented
Funny, this PR either breaks Darwin (Mach-O) emitter or highlights a problem in it (I didn't touch the format emitters). Even `Red/System [] probe "hello world"` segfaults with `-t Darwin`, though all big enough scripts seem to be okay. `-t MacOS` is OK too.

2020-11-17 18:51 UTC, hiiamboris commented
No, sorry. This is some VMWare glitch related to file caching. Weird issue.

2020-11-17 19:57 UTC, hiiamboris commented
So, about failing "#3999-D" and "33999-F" tests: they never worked on Mac in the first place. Both return a NaN instead of `23.0`. `FFC00000h` instead of float-32 23.0, and `FFF80000 00000000` instead of float-64 23.0. It just happened that the previous IA-32 emitter treated `nan = 23.0` as true expression.

2020-11-17 20:09 UTC, hiiamboris commented
https://github.com/red/red/issues/4726

2020-11-20 12:25 UTC, dockimbel commented on system/targets/IA-32.r
> +
This function cannot be accepted in its current form. The hidding implicit data passing style is obfuscation. Please pass the data you need by regular arguments and return a block of values.

Moreover, I can't make sense of the following code:
```
o: do reduce [pick [to-bin8 to-bin32] short?  'o]
```
It evaluates one of the two conversion function, but without an argument?

I think you should rewrite more cleanly this function or redesign properly the whole `emit-branch` function.

2020-11-20 12:38 UTC, dockimbel commented on runtime/macros.reds
> +		if any [fl/value > 2147483647.0 fl/value < -2147483648.0 fl/value <> fl/value][
That addition deserves a pretty good comment at least. ;-)

2020-11-20 13:11 UTC, hiiamboris commented on system/targets/IA-32.r
> +
`do reduce [pick [to-bin8 to-bin32] short?  'o]` -> `do [to-bin8 o]` or `do [to-bin32 o]`

2020-11-20 19:25 UTC, greggirwin commented on system/targets/IA-32.r
> +
How about `either short? [to-bin8 o][to-bin32 o]` ? Saves `do + reduce` and is blatantly obvious.

2020-11-20 19:27 UTC, greggirwin commented on system/targets/IA-32.r
> +
I'm not a fan of `pick` for binary choices in general. Sometimes yet, but not often.

2020-11-20 20:48 UTC, hiiamboris commented on system/targets/IA-32.r
> +
:+1:

2020-11-22 19:35 UTC, greggirwin commented on system/targets/IA-32.r
> +		o: do jmpofs: [size * pick [-1 1] yes = back?]	;-- convert size to signed jump offset
Please add a comment about the thunk-like use of `jmpofs`. Took me a minute to find it and see how it was used.

2020-11-22 19:56 UTC, hiiamboris commented on system/targets/IA-32.r
> +		o: do jmpofs: [size * pick [-1 1] yes = back?]	;-- convert size to signed jump offset
In real code (not in diff) it's just a few lines above. Can't miss it. Not sure what kind of comment you expect ;)

2020-11-22 19:59 UTC, greggirwin commented on system/targets/IA-32.r
> +		o: do jmpofs: [size * pick [-1 1] yes = back?]	;-- convert size to signed jump offset
OK. I was thinking something like "jmpofs is used to recalc later after size is adjusted."

2020-11-22 22:41 UTC, greggirwin commented
:+1:

2021-05-13 11:27 UTC, dockimbel commented on system/targets/IA-32.r
> +					][ op ]
Why did you change the coding style of line 1336?

2021-05-13 11:45 UTC, dockimbel requested changes
Is ARM backend fully supported now?

2021-05-13 11:45 UTC, dockimbel commented on system/targets/IA-32.r
> +			unord-jumps-to-true?: either flip? [		;-- should unordered JP jump lead to true branch?
`unord-jumps-to-true?` is way too big name. It's like trying to fit a whole comment line into a variable's name... Please use a short name and let the comment line explain its purpose and usage.

2021-05-13 11:45 UTC, dockimbel commented on system/targets/IA-32.r
> +			set psize size							;-- update size in the caller
There is still some obfuscated data-passing between the caller and this function using a word (`size`) bound in calling context. That's really a confusing style we don't want to have here. The code logic is already complicated enough. Just return it in the return block (yes, you need to change the way that returned block is used then, maybe the binary code forming should happen here and just return the formed bytes and size).

2021-05-13 17:54 UTC, greggirwin commented on system/targets/IA-32.r
> +			unord-jumps-to-true?: either flip? [		;-- should unordered JP jump lead to true branch?
@dockimbel please suggest a name you want. Otherwise we just keep guessing. Personally I don't think this name is too long, and it's clear without a comment.

2021-05-13 17:57 UTC, greggirwin commented on system/targets/IA-32.r
> +					][ op ]
The new format actually reads better to me. The original is very dense. But then I'm also not a fan of `pick` used for logic options because I think it's less clear.

2021-05-13 19:25 UTC, hiiamboris commented on system/targets/IA-32.r
> +			set psize size							;-- update size in the caller
Hmm. I think it's no more confusing that `incr: func [word] [set word 1 + get word]` or any other function that works with words. But okay, I'll make it super verbose ☺

2021-05-13 19:35 UTC, hiiamboris commented
> 
> 
> Is ARM backend fully supported now?

Yes. I think it fails due to issue you fixed recently with IDIV.

2021-05-13 19:37 UTC, hiiamboris commented on system/targets/IA-32.r
> +					][ op ]
IIRC because the line didn't fit into 56 chars and I wanted to align comments.

2021-05-13 19:43 UTC, hiiamboris commented on system/targets/IA-32.r
> +			set psize size							;-- update size in the caller
```
		jxx: [second set [size jump-code] construct-jump op      size back?]
		jp:  [second set [size jump-code] construct-jump 'parity size back?]
```
`jump-code` is never used but kind of tells what `second` returns here.

2021-05-20 13:11 UTC, dockimbel commented on system/targets/IA-32.r
> +			unord-jumps-to-true?: either flip? [		;-- should unordered JP jump lead to true branch?
I'll retract my comment on this one, as that longer name is a minor annoyance to me, compared to the previous one with special symbol in it.

2021-05-20 13:14 UTC, dockimbel commented on system/targets/IA-32.r
> +					][ op ]
> The new format actually reads better to me. The original is very dense. But then I'm also not a fan of `pick` used for logic options because I think it's less clear.

It's supposed to be dense, so that all the related code fits into one page in a code editor, in order to make it easier to reason about when debugging or upgrading it.

2021-05-20 13:15 UTC, merged

2021-05-23 21:15 UTC, greggirwin commented on system/targets/IA-32.r
> +					][ op ]
The great thing about code is that one person's "dense" is another's "makes me feel dense."